Tidy up spec and add GH workflow

diff --git a/.github/workflows/e2e.yaml b/.github/workflows/e2e.yaml
--- a/.github/workflows/e2e.yaml
+++ b/.github/workflows/e2e.yaml
@@ -7,9 +7,7 @@ on:
     branches: [main, master]
 
 env:
-  TEST_PAGE_ORIGIN: https://www.abc.net.au
-  TEST_LOCAL_SERVER: http://localhost:8000
-  AUNTY_HOST: localhost
+  AUNTY_HOST: localhost # This tells aunty to serve on localhost
   TERMINUS_FETCH_API_KEY: ${{ secrets.TERMINUS_FETCH_API_KEY }}
 
 jobs:
@@ -21,19 +19,32 @@ jobs:
         uses: actions/setup-node@v4
         with:
           node-version: '20.x'
-      # - uses: actions/cache@v1
-      #   with:
-      #     path: ~/.cache/pip
-      #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
-      #     restore-keys: |
-      #       ${{ runner.os }}-pip-
       - run: npm ci
       - run: npx playwright install --with-deps
       - run: echo "TERMINUS_FETCH_API_KEY=$TERMINUS_FETCH_API_KEY" > .env
-      - run: npm test
+      - name: Run Playwright tests
+        run: |
+          npm run test | tee output.log
+          if grep -q -e "Error: A snapshot doesn't exist at" -e "Screenshot comparison failed" output.log; then
+            echo "Playwright tests failed due to a snapshot issue."
+            echo "SNAPSHOT_DIFFERENCES=true" >> $GITHUB_ENV
+            exit 1
+          elif grep -q "failed" output.log; then
+            echo "Playwright tests failed due to a non-snapshot issue."
+            exit 1
+          fi
       - uses: actions/upload-artifact@v4
+        id: artifact-upload
         if: ${{ !cancelled() }}
         with:
           name: playwright-report
           path: playwright-report/
           retention-days: 30
+      - name: Comment on PR with report link
+        uses: thollander/actions-comment-pull-request@v3
+        if: ${{ failure() && env.SNAPSHOT_DIFFERENCES == 'true' }}
+        with:
+          message: |
+            ### Playwright visual snapshot differences were detected.
+            View the [Playwright report](${{ steps.artifact-upload.outputs.artifact-url }}) to review the visual differences.
+            **To approve the snapshot changes and update the snapshots, please comment:** /approve-snapshots
